services:
  - type: web
    name: aimm-langflow
    env: docker
    image: langflowai/langflow:latest  # Usa a imagem oficial sem precisar de Dockerfile
    plan: starter
    envVars:
      - key: LANGFLOW_DATABASE_URL
        value: postgresql://aimmob:aimmob123@aimm-postgres:5432/aimmobdb
      - key: LANGFLOW_CONFIG_DIR
        value: /app/langflow
    startCommand: ["langflow", "run"]
    ports:
      - 7860
    healthCheckPath: "/"
    disk:
      name: langflow-storage
      mountPath: /app/langflow

  - type: web
    name: aimm-pgadmin
    env: docker
    image: dpage/pgadmin4:latest  # Usa a imagem oficial do PgAdmin
    plan: starter
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: comercial@aimmob.com.br
      - key: PGADMIN_DEFAULT_PASSWORD
        value: aimmob123
    ports:
      - 80
    disk:
      name: pgadmin-storage
      mountPath: /var/lib/pgadmin
